### ISSUE TITLE
Looking to contribute to TBC

### ISSUE THREAD

**Issue by topkek-addons** [vendethiel/GladiusEx#36]
Hi ven,

I would love to collaborate with you on the TBC version of GladiusEx. If there is any extra work you need help with, I am here. If you are interested we can discuss further on Discord (Topkek#ooo1) -- The o's are 0s but GitHub is weird... I figure it is easier for us to use an IM mode of communication rather than issues/pull requests. This would also help me understand what work is still open.

Thanks!

**Comment by vendethiel** [comment]
Sent you a discord invite.
As per master of LibCooldownTracker+this repo, most features should work fine in TBC.

Big lines are:
- Add racials to LibCooldownTracker (cooldowns_bcc_racials)
- Add trinket(s) to LibCooldownTracker (cooldowns_bcc_items)
- Add more important auras (since I just took the retail ones and removed post-BC auras)
- Investigate bug where sometimes party frames don't appear
- Make sure /reload doesn't break the addon once in the arena
- Combat indicator
- Add LibHealComm support if the user has it for party frames

I think things like shadowsight timers can be done via WA and don't really belong in the addon (we only show things about players).

**Comment by topkek-addons** [comment]
Sounds good. Agreed on the shadowsight timers.
